### ISSUE TITLE
For Beginners

### ISSUE THREAD

**Issue by Blackei** [pmpkk/openhab-findmyiphone-api#1]
Hi,
You made this what i Looking for.....
I installed OpenHab on my Synology and have 2 IPhones 
You wrote one File Must copy to scripts but what is with The other Files?

And can i use this for 2 IPhone? Or can i use them only together?

Thanks

Lars

**Comment by pmpkk** [comment]
Fixed, you need to copy three files.

You can add as many accounts and devices as you want.

**Comment by Blackei** [comment]
Hi,
Doesn‘t work on Synology 

/usr/bin/python /volume1/@appstore/openHAB2/conf/scripts/apple.py setup
Traceback (most recent call last):
  File "/volume1/@appstore/openHAB2/conf/scripts/apple.py", line 7, in <module>
    import requests
ImportError: No module named requests
